base_path: /

routes:
  index: [/, Api.index, GET]
  api: [/api, Api.api, GET]
  riegos: [/api/riegos, Api.volumen, GET]
  volumen: [/api/volumen, Api.volumen, GET]
  program: [/api/program, Api.program, GET]
  socket: [/socket, Api.socket, GET]
